# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_image', models.ImageField(blank=True, default=None, height_field='height_field', null=True, upload_to='Images/Groups', verbose_name='Group Logo', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=150, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Group Description')),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'verbose_name': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_logo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='Images/', verbose_name='Organization Logo', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=150, verbose_name='Organization Name')),
                ('description', models.TextField(default=None, verbose_name='Description')),
                ('created_on', models.DateField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('organization_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_avatar', models.ImageField(blank=True, default=None, height_field='height_field', null=True, upload_to='Images/Avatars', verbose_name='Avatar', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(default=None, max_length=150, verbose_name='First Name')),
                ('lastname', models.CharField(default=None, max_length=200, verbose_name='Surname')),
                ('email', models.EmailField(default=None, max_length=100, unique=True, verbose_name='Email Address')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('user_type', models.CharField(choices=[('SU', 'Super User'), ('AD', 'Admin'), ('US', 'User')], default='US', max_length=10, verbose_name='User Type')),
                ('organizations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organization_Users', to='Organizations.Organizations')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, related_name='Group_Users', to='Organizations.Users'),
        ),
    ]
