# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_auto_20170327_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='organization_owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Organizations.Users'),
            preserve_default=False,
        ),
    ]
