# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_auto_20170321_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='Images/Groups', verbose_name='Group Logo', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=150, verbose_name='Group Name')),
                ('description', models.TextField(verbose_name='Group Description')),
                ('organizations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organization', to='Organizations.Organizations')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='Images/Avatars', verbose_name='Avatar', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('first_name', models.CharField(default=None, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(default=None, max_length=200, verbose_name='Surname')),
                ('email_address', models.CharField(default=None, max_length=100, verbose_name='Email Address')),
                ('password', models.CharField(default='password', max_length=20, verbose_name='Password')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group_Users', to='Organizations.Groups')),
                ('organizations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organization_Users', to='Organizations.Organizations')),
            ],
        ),
    ]
