# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_auto_20170327_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='organization_owner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
