# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0004_groups_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='description',
            field=models.TextField(default=None, verbose_name='Group Description'),
        ),
    ]
