# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_auto_20170321_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='project_image',
            field=models.ImageField(blank=True, default=None, height_field='height_field', null=True, upload_to='Images/Groups', verbose_name='Group Logo', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='users',
            name='project_image',
            field=models.ImageField(blank=True, default=None, height_field='height_field', null=True, upload_to='Images/Avatars', verbose_name='Avatar', width_field='width_field'),
        ),
    ]
