# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0006_auto_20170327_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='username_field',
        ),
    ]
