# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0007_auto_20170328_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username_field',
            new_name='username',
        ),
    ]
