# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizations', '0008_auto_20170321_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='organization_owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
