# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0009_organizations_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='simillar',
            field=models.ManyToManyField(blank=True, related_name='_users_simillar_+', to='Organizations.Users'),
        ),
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(related_name='Group_Users', to='Organizations.Groups'),
        ),
    ]
