# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0012_auto_20170321_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='project_image',
            new_name='group_image',
        ),
        migrations.RenameField(
            model_name='organizations',
            old_name='project_image',
            new_name='organization_logo',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='project_image',
            new_name='user_avatar',
        ),
    ]
