# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0013_auto_20170321_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.AddField(
            model_name='groups',
            name='users',
            field=models.ManyToManyField(related_name='Group_Users', to='Organizations.Users'),
        ),
    ]
