# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0015_auto_20170324_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='project',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
