# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0013_auto_20170325_0211'),
        ('Organizations', '0016_groups_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='project',
        ),
        migrations.AddField(
            model_name='groups',
            name='projects',
            field=models.ManyToManyField(default=None, related_name='Group_projects', to='Project.Projects'),
        ),
        migrations.AddField(
            model_name='users',
            name='projects',
            field=models.ManyToManyField(default=None, related_name='user_projects', to='Project.Projects'),
        ),
    ]
