# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0017_auto_20170325_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='users',
            name='projects',
        ),
    ]
