# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=150, verbose_name='Task Title')),
                ('due_date', models.DateField(default=django.utils.timezone.now, verbose_name='Due Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Task Notes')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Projects')),
                ('sub_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.SubProject')),
            ],
        ),
    ]
