# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='sub_project',
        ),
    ]
