# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_auto_20170311_2202'),
        ('Tasks', '0002_remove_tasks_sub_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='sub_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.SubProject'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Projects'),
        ),
    ]
