# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-12 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_auto_20170312_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projecttasks', to='Project.Projects'),
        ),
    ]
