# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-15 19:08
from __future__ import unicode_literals

from django.db import migrations
import livefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_auto_20170312_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='live',
            field=livefield.fields.LiveField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together=set([('title', 'live')]),
        ),
    ]
