# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_files_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='images',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
