# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0009_auto_20170317_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file',
            new_name='file_url',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='files',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskfiles', to='Tasks.Tasks'),
        ),
        migrations.AlterField(
            model_name='images',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskimages', to='Tasks.Tasks'),
        ),
    ]
