# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0010_auto_20170318_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Due Date'),
        ),
    ]
