# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 02:29
from __future__ import unicode_literals

from django.db import migrations
import livefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0013_auto_20170318_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='live',
            field=livefield.fields.LiveField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='tasks',
            unique_together=set([('title', 'live')]),
        ),
    ]
