# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0015_auto_20170318_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
