# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='project_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='Images/Groups', verbose_name='Group Logo', width_field='width_field'),
        ),
    ]
