# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Groups', '0001_initial'),
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(default=None, max_length=200, verbose_name='Surname')),
                ('project_image', models.ImageField(blank=True, default='Images/None/no-img.gif', height_field='height_field', null=True, upload_to='Images/Avatars', verbose_name='Avatar', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('password', models.CharField(default='password', max_length=20, verbose_name='Password')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Group_Users', to='Groups.Groups')),
                ('organizations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organization_Users', to='Organizations.Organizations')),
            ],
        ),
    ]
