# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='Project Name')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Completion Date')),
                ('project_image', models.ImageField(blank=True, default='Images/None/no-img.gif', height_field='height_field', null=True, upload_to='Images/', verbose_name='Project Image', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Project Description')),
                ('github_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Github Repo Url')),
                ('project_type', models.CharField(choices=[('GP', 'General Project'), ('NAA', 'Advertisement Account'), ('MA', 'Marketing'), ('ND', 'Design'), ('NW', 'Website')], default='GP', max_length=30, verbose_name='Project Type')),
                ('project_status', models.CharField(choices=[('O', 'Open'), ('C', 'Contract'), ('IDF', 'Initial Design Draft'), ('CO', 'Coding'), ('SO', 'Seo Optimization'), ('M', 'Maintanence'), ('CLSD', 'Contract')], default='O', max_length=30, verbose_name='Project Status')),
                ('groups', models.ManyToManyField(blank=True, default=None, related_name='project_groups', to='Organizations.Groups')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.Organizations')),
                ('users', models.ManyToManyField(blank=True, default=None, to='Organizations.Users')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'verbose_name': 'Project',
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sub-project Name')),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Completion Date')),
                ('groups', models.ManyToManyField(blank=True, default=None, to='Organizations.Groups')),
                ('projects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='Project.Projects')),
                ('users', models.ManyToManyField(blank=True, default=None, to='Organizations.Users')),
            ],
            options={
                'verbose_name_plural': 'Sub-Projects',
                'verbose_name': 'Sub-Project',
            },
        ),
    ]
