# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Project Name')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Completion Date')),
                ('project_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', verbose_name='Project Image', width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('description', models.TextField(verbose_name='Project Description')),
                ('github_url', models.CharField(max_length=200, verbose_name='Github Repo Url')),
            ],
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sub-project Name')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Completion Date')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Projects')),
            ],
        ),
    ]
