# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-11 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='github_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Github Repo Url'),
        ),
    ]
