# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20170312_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='sub_projects',
        ),
        migrations.AddField(
            model_name='subproject',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Projects'),
        ),
    ]
