# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20170312_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(blank=True, default='Images/None/no-img.gif', height_field='height_field', null=True, upload_to='Images/', verbose_name='Project Image', width_field='width_field'),
        ),
    ]
