# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_auto_20170317_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subproject',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
