# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0014_auto_20170322_1834'),
        ('Project', '0009_auto_20170321_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='group',
        ),
        migrations.AddField(
            model_name='projects',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, to='Organizations.Groups'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, to='Organizations.Groups'),
        ),
    ]
