# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_auto_20170322_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={'verbose_name': 'Sub-Project', 'verbose_name_plural': 'Sub-Projects'},
        ),
    ]
