# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_auto_20170323_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='organization',
        ),
    ]
