# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0012_remove_subproject_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='users',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='users',
        ),
    ]
