# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_auto_20170325_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, related_name='project_groups', to='Organizations.Groups'),
        ),
    ]
